cosmos.cassandra:
  base-packages: com.azure.cosmos.cassandra.example.data
  contact-point: ${azure.cosmos.cassandra.global-endpoint}
  keyspace: azure_cosmos_cassandra_driver_4_examples
  schema-action: CREATE_IF_NOT_EXISTS

  auth-provider:
    # By default we use the PlainTextAuthProvider (see reference.conf) and specify the username and password here.
    username: ${azure.cosmos.cassandra.username}
    password: ${azure.cosmos.cassandra.password}

  load-balancing-policy:

    # Cosmos load balancing policy parameters
    #
    #   Update this file or run this example with these system properties set to override the values provided here:
    #
    #   -Ddatastax-java-driver.basic.load-balancing-policy.multi-region-writes=[true|false]
    #   -DDdatastax-java-driver.basic.load-balancing-policy.preferred-regions=[<region-name>[,...]|[]]
    #
    #   Alternatively, set the environment variables referenced here to match the topology and preferences for your
    #   Cosmos DB Cassandra API instance.

    multi-region-writes: ${azure.cosmos.cassandra.multi-region-writes:false}

    preferred-regions: ${azure.cosmos.cassandra.preferred-regions:null}

  retry-policy:
    # By default we use the CosmosRetryPolicy (see reference.conf) and accept the default configuration here.

logging:
  file:
    name: ${azure.cosmos.cassandra.log-file:${user.home}/.local/var/log/azure-cosmos-cassandra-spring-boot-app-example.log}
  logback:
    rollingpolicy:
      max-file-size: 10GB
  pattern:
    console:

spring:
  main:
    banner-mode: off
